
# ENVIRONMENT VARIABLES NAMES
ENABLE_PROFILING_ENVIRONMENT_VARIABLE_NAME = 'ENABLE_PROFILING'
MAX_LINKS_TO_VISIT_ENVIRONMENT_VARIABLE_NAME = 'MAX_LINKS_TO_VISIT'
OPENAI_API_KEY_ENVIRONMENT_VARIABLE_NAME = 'OPENAI_API_KEY'
IS_PROFILED_ATTRIBUTE_NAME = 'is_profiled'
BENCHMARK_RESULTS_DIRECTORY_NAME = 'benchmark_results'
